
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Oct 07 23:59:01 CEST 2019
//----------------------------------------------------

package askov.schoolprojects.compilerconstruction.mjcompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int CONST = 5;
  public static final int CHAR = 13;
  public static final int LPAREN = 17;
  public static final int SEMI = 6;
  public static final int CONTINUE = 25;
  public static final int DECR = 21;
  public static final int INT = 11;
  public static final int INCR = 20;
  public static final int MINUS = 30;
  public static final int RPAREN = 18;
  public static final int AND = 37;
  public static final int LT = 42;
  public static final int OR = 36;
  public static final int BOOL = 12;
  public static final int COMMA = 9;
  public static final int CLASS = 7;
  public static final int DIV = 33;
  public static final int GEQ = 41;
  public static final int PLUS = 35;
  public static final int ASSIGN = 10;
  public static final int IF = 22;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int RBRACKET = 15;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 34;
  public static final int NEQ = 39;
  public static final int BREAK = 24;
  public static final int IDENT = 4;
  public static final int VOID = 19;
  public static final int EQ = 38;
  public static final int ERROR = 46;
  public static final int TIMES = 32;
  public static final int ELSE = 44;
  public static final int LBRACE = 3;
  public static final int READ = 27;
  public static final int WHILE = 23;
  public static final int RBRACE = 8;
  public static final int EXTENDS = 16;
  public static final int LEQ = 43;
  public static final int GT = 40;
  public static final int DO = 45;
  public static final int PRINT = 28;
}

